const sampleListing=[
  {
    title: "Sunrise PG for Men",
    description: "Clean shared PG with furnished beds, wardrobe, WiFi and housekeeping.",
    image: "https://images.pexels.com/photos/3933240/pexels-photo-3933240.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 8500,
    location: "Koramangala, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Green Leaf Ladies PG",
    description: "Comfortable furnished PG with clean rooms, storage and common facilities.",
    image: "https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 7200,
    location: "Madhapur, Hyderabad",
    State: "Telangana",
    category: "PG",
  },
  {
    title: "Urban Nest PG",
    description: "Modern shared accommodation with twin beds, study space and natural lighting.",
    image: "https://images.pexels.com/photos/14784255/pexels-photo-14784255.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 9500,
    location: "HSR Layout, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Royal Stay PG",
    description: "Affordable furnished PG with comfortable beds, wardrobe and clean interiors.",
    image: "https://images.pexels.com/photos/7745944/pexels-photo-7745944.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 6800,
    location: "BTM Layout, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Blossom Girls PG",
    description: "Bright and clean shared PG with modern furniture and spacious interiors.",
    image: "https://images.pexels.com/photos/20604664/pexels-photo-20604664.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 7800,
    location: "Indiranagar, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Metro View PG",
    description: "Well-furnished shared accommodation with twin beds and dedicated workspace.",
    image: "https://images.pexels.com/photos/9889754/pexels-photo-9889754.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 9000,
    location: "Andheri West, Mumbai",
    State: "Maharashtra",
    category: "PG",
  },
  {
    title: "Comfort Homes PG",
    description: "Simple and clean PG accommodation with comfortable beds and storage.",
    image: "https://images.pexels.com/photos/26729320/pexels-photo-26729320.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 7500,
    location: "Marathahalli, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Elite Living PG",
    description: "Premium shared accommodation with modern interiors and comfortable furnishings.",
    image: "https://images.pexels.com/photos/7722153/pexels-photo-7722153.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 11000,
    location: "Kondapur, Hyderabad",
    State: "Telangana",
    category: "PG",
  },
  {
    title: "Campus Comfort PG",
    description: "Student-friendly PG with clean beds, desk space and natural light.",
    image: "https://images.pexels.com/photos/15477636/pexels-photo-15477636.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 6000,
    location: "Kothrud, Pune",
    State: "Maharashtra",
    category: "PG",
  },
  {
    title: "Prime Comfort PG",
    description: "Modern furnished PG with comfortable beds, wardrobe and neat interiors.",
    image: "https://images.pexels.com/photos/10130812/pexels-photo-10130812.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 8200,
    location: "Bellandur, Bengaluru",
    State: "Karnataka",
    category: "PG",
  },
  {
    title: "Cozy Corner Room",
    description: "Private furnished room with a comfortable bed, wardrobe and natural lighting.",
    image: "https://images.pexels.com/photos/35382792/pexels-photo-35382792.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 10500,
    location: "Electronic City, Bengaluru",
    State: "Karnataka",
    category: "Room",
  },
  {
    title: "Lakeview Private Room",
    description: "Peaceful private bedroom with modern furniture and a clean minimalist interior.",
    image: "https://images.pexels.com/photos/6987719/pexels-photo-6987719.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 12000,
    location: "Whitefield, Bengaluru",
    State: "Karnataka",
    category: "Room",
  },
  {
    title: "Modern Studio Room",
    description: "Minimal private bedroom with comfortable bed, side table and workspace.",
    image: "https://images.pexels.com/photos/11125421/pexels-photo-11125421.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 13500,
    location: "HSR Layout, Bengaluru",
    State: "Karnataka",
    category: "Room",
  },
  {
    title: "City View Room",
    description: "Bright private room with clean furniture and a spacious modern interior.",
    image: "https://images.pexels.com/photos/6920600/pexels-photo-6920600.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 11500,
    location: "Powai, Mumbai",
    State: "Maharashtra",
    category: "Room",
  },
  {
    title: "Peaceful Stay Room",
    description: "Quiet furnished bedroom with natural light, wardrobe and comfortable bed.",
    image: "https://images.pexels.com/photos/7745932/pexels-photo-7745932.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 10000,
    location: "Baner, Pune",
    State: "Maharashtra",
    category: "Room",
  },
  {
    title: "Urban Private Room",
    description: "Modern private bedroom with clean furniture and a simple elegant design.",
    image: "https://images.pexels.com/photos/20854915/pexels-photo-20854915.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 12500,
    location: "Gachibowli, Hyderabad",
    State: "Telangana",
    category: "Room",
  },
  {
    title: "Bright Living Room",
    description: "Well-lit private bedroom with comfortable bed, storage and workspace.",
    image: "https://images.pexels.com/photos/10130817/pexels-photo-10130817.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 9000,
    location: "Kalyan Nagar, Bengaluru",
    State: "Karnataka",
    category: "Room",
  },
  {
    title: "Premium Comfort Room",
    description: "Spacious private bedroom with modern furniture and clean interiors.",
    image: "https://images.pexels.com/photos/15477636/pexels-photo-15477636.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 14500,
    location: "Kharadi, Pune",
    State: "Maharashtra",
    category: "Room",
  },
  {
    title: "Elegant Private Room",
    description: "Clean private bedroom with modern furniture, wardrobe and soft lighting.",
    image: "https://images.pexels.com/photos/26729320/pexels-photo-26729320.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 11000,
    location: "Indiranagar, Bengaluru",
    State: "Karnataka",
    category: "Room",
  },
  {
    title: "Minimal Studio Room",
    description: "Bright private bedroom with simple furniture, natural light and clean design.",
    image: "https://images.pexels.com/photos/6987719/pexels-photo-6987719.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 13000,
    location: "Madhapur, Hyderabad",
    State: "Telangana",
    category: "Room",
  },
  {
    title: "Campus Hub Hostel",
    description: "Affordable hostel with clean bunk beds, storage and shared dormitory space.",
    image: "https://images.pexels.com/photos/5137980/pexels-photo-5137980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4500,
    location: "Jayanagar, Bengaluru",
    State: "Karnataka",
    category: "Hostel",
  },
  {
    title: "Backpackers Central Hostel",
    description: "Clean dormitory with comfortable bunk beds, lockers and shared facilities.",
    image: "https://images.pexels.com/photos/4907236/pexels-photo-4907236.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4000,
    location: "Viman Nagar, Pune",
    State: "Maharashtra",
    category: "Hostel",
  },
  {
    title: "Student Square Hostel",
    description: "Budget hostel with organized bunk beds, storage and clean shared interiors.",
    image: "https://images.pexels.com/photos/5158462/pexels-photo-5158462.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 5000,
    location: "Kukatpally, Hyderabad",
    State: "Telangana",
    category: "Hostel",
  },
  {
    title: "Urban Dorm Hostel",
    description: "Modern dormitory with wooden bunk beds, individual spaces and storage.",
    image: "https://images.pexels.com/photos/7969094/pexels-photo-7969094.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4200,
    location: "Indiranagar, Bengaluru",
    State: "Karnataka",
    category: "Hostel",
  },
  {
    title: "City Backpacker Hostel",
    description: "Simple shared hostel with clean bunk beds and comfortable dormitory space.",
    image: "https://images.pexels.com/photos/4907429/pexels-photo-4907429.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 3800,
    location: "Bandra, Mumbai",
    State: "Maharashtra",
    category: "Hostel",
  },
  {
    title: "Scholar's Stay Hostel",
    description: "Student-focused hostel with organized dormitory beds and shared facilities.",
    image: "https://images.pexels.com/photos/4907209/pexels-photo-4907209.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4800,
    location: "Rajajinagar, Bengaluru",
    State: "Karnataka",
    category: "Hostel",
  },
  {
    title: "Metro Nest Hostel",
    description: "Comfortable dormitory accommodation with bunk beds and personal storage.",
    image: "https://images.pexels.com/photos/4907433/pexels-photo-4907433.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4300,
    location: "Ameerpet, Hyderabad",
    State: "Telangana",
    category: "Hostel",
  },
  {
    title: "The Social Hostel",
    description: "Clean modern hostel with multiple bunk beds and organized sleeping spaces.",
    image: "https://images.pexels.com/photos/7969104/pexels-photo-7969104.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 5200,
    location: "Koregaon Park, Pune",
    State: "Maharashtra",
    category: "Hostel",
  },
  {
    title: "Comfort Dorm Hostel",
    description: "Affordable shared hostel with clean bunk beds and simple interiors.",
    image: "https://images.pexels.com/photos/5158461/pexels-photo-5158461.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4500,
    location: "Koramangala, Bengaluru",
    State: "Karnataka",
    category: "Hostel",
  },
  {
    title: "Urban Student Hostel",
    description: "Modern student hostel with clean dormitory beds, storage and shared spaces.",
    image: "https://images.pexels.com/photos/4907425/pexels-photo-4907425.jpeg?auto=compress&cs=tinysrgb&w=1200",
    price: 4900,
    location: "Kondapur, Hyderabad",
    State: "Telangana",
    category: "Hostel",
  },
];
module.exports={data:sampleListing};